# Generated by Django 3.1.3 on 2020-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='community',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='community_email',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='community_link',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='community_phone',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='community_role',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
