# Generated by Django 3.1.3 on 2020-11-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='community',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='authuser',
            name='community_role',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
