# Generated by Django 3.1.3 on 2020-11-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201114_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='community_email',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='authuser',
            name='community_link',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AddField(
            model_name='authuser',
            name='community_phone',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
