# Generated by Django 3.1.3 on 2020-11-19 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201119_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
