# Generated by Django 3.1.3 on 2020-11-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201115_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='landzones',
            field=models.JSONField(default=dict),
        ),
    ]
