# Generated by Django 3.1.3 on 2020-11-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landzones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landzone',
            name='geo_json',
            field=models.JSONField(default=None, verbose_name='geo json'),
        ),
        migrations.AddField(
            model_name='landzone',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landzone',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
